name: 'shopstream_analytics'
version: '1.0.0'

profile: 'shopstream_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]




clean-targets:        
  - "target"
  - "dbt_packages"

models:
  shopstream_analytics:
   
    example:
      +materialized: view

    silver:
      +materialized: incremental
      +tags: ['silver']
    gold:
      +materialized: table
      +tags: ['gold']
