version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]

  - name: dim_products
    columns:
      - name: product_id
        tests: [unique, not_null]

  - name: fct_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

  - name: fct_order_items
    columns:
      - name: order_item_id
        tests: [unique, not_null]
      - name: order_id
        tests:
          - relationships:
              to: ref('fct_orders')
              field: order_id
      - name: product_id
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_id

  - name: agg_orders_daily
    columns:
      - name: order_date
        tests: [not_null]

  - name: agg_events_daily
    columns:
      - name: event_date
        tests: [not_null]

