version: 2

models:
  - name: customers
    description: "Cleaned and normalized customer data from bronze layer"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer's first name"
      - name: last_name
        description: "Customer's last name"
      - name: email
        description: "Customer's email address"
        tests:
          - unique
          - not_null
      - name: created_at
        description: "Timestamp when the customer record was created"
      - name: updated_at
        description: "Timestamp when the customer record was last updated"

  - name: products
    description: "Cleaned and normalized product data from bronze layer"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: name
        description: "Product name"
      - name: description
        description: "Product description"
      - name: price
        description: "Product price"
        tests:
          - not_null
      - name: category
        description: "Product category"
      - name: created_at
        description: "Timestamp when the product record was created"
      - name: updated_at
        description: "Timestamp when the product record was last updated"

  - name: orders
    description: "Cleaned and normalized order data from bronze layer"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      - name: total_amount
        description: "Total order amount"
        tests:
          - not_null
      - name: status
        description: "Order status"
      - name: created_at
        description: "Timestamp when the order record was created"
      - name: updated_at
        description: "Timestamp when the order record was last updated"

  - name: order_items
    description: "Cleaned and normalized order items data from bronze layer"
    columns:
      - name: order_item_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to orders"
        tests:
          - not_null
          - relationships:
              to: ref('orders')
              field: order_id
      - name: product_id
        description: "Foreign key to products"
        tests:
          - not_null
          - relationships:
              to: ref('products')
              field: product_id
      - name: quantity
        description: "Quantity of product ordered"
        tests:
          - not_null
      - name: unit_price
        description: "Price per unit at time of order"
        tests:
          - not_null
      - name: created_at
        description: "Timestamp when the order item record was created"

  - name: events
    description: "Cleaned and normalized event data from bronze layer"
    columns:
      - name: event_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: event_type
        description: "Type of event"
        tests:
          - not_null
      - name: event_data
        description: "JSON data associated with the event"
      - name: created_at
        description: "Timestamp when the event occurred"
        tests:
          - not_null