version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: raw_events
        description: "Raw events from Kafka streams"
        columns:
          - name: topic
            description: "Kafka topic name"
          - name: record_key
            description: "Kafka message key"
          - name: record_value
            description: "JSON payload from Kafka message"
          - name: partition
            description: "Kafka partition number"
          - name: offset
            description: "Kafka message offset"
          - name: event_ts
            description: "Event timestamp"
          - name: ingested_at
            description: "Ingestion timestamp"